### ISSUE TITLE
install-report failing during npm install: missing file

### ISSUE THREAD

**Issue by focusaurus** [tinganho/l10ns#107]
> l10ns@2.0.23 install /home/footprintid/Footprintid/node_modules/l10ns
    > node binaries/install-report.js

    module.js:340
        throw err;
              ^
    Error: Cannot find module '/home/footprintid/Footprintid/node_modules/l10ns/binaries/install-report.js'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:935:3

* are you packaging things correctly for npm?
* I would vote strongly to remove this "feature". Get your analytics out of my deploys.

**Comment by tinganho** [comment]
I can't reproduce this? in npm v2.3 and v2.7.4 and node v0.11.16 and v.12.2. I also checked that the files are there.

Are you disturb because of the potential privacy issue?

This analytics just report the installation to Google Analytics. This is my only reliable stats for downloads of L10ns. Since NPM or npm-stat doesn't provide any reliable stats. One day it could be over a thousand and next day 1 download.

I don't think it is violating any privacy since its mirroring what NPM does? NPM store analytics of how many request goes to one resource. I'm just doing the same thing but more reliably.

I also collect analytics for the l10ns command. so if you do `l10ns update`. It would report to GA as if you would visit a website on path `/update`. No personal data is collected. Just check the `binaries/l10ns` file after `track(...)` to see where I report things.

I hope I didn't step on someone's foot doing this.

**Comment by focusaurus** [comment]
> Are you disturb because of the potential privacy issue?

Somewhat, but more importantly I'm disturbed by unnecessary code running at install time and accessing the Internet that isn't strictly required to get me the bits I need to do my job. I also fail to see how number of downloads/installs has any analytical utility given CI builds, npm cache, etc. But I digress.

I also want to nip any precedent in the bud here. This is not something I want nor need from the npm ecosystem and the only other time I've seen it is bower and bower is finally dying a well-deserved death.

Partially this is probably pent up frustration because for mysterious reasons I have not yet successfully debugged/reproduced, `l10ns` is the single least reliable npm install I have done out of many hundreds of packages. The more recent versions have been installing pretty reliably on OSX but for whatever reason my production linux servers always choke on it.

I'm running node v0.10.37 and npm 1.4.28 on a low-memory Ubuntu 12.04.5 EC2 instance.

Where are these "no such file" issues coming from? There have been several variations of this same thing. It would be one thing if this was an intermittent network error, but I don't get these missing file issues. Are there bad tarballs in the npm registry?

**Comment by tinganho** [comment]
@focusaurus I can try to remove the `install-report` I think I can live without the analytics. 

You're right the installation of `L10ns` haven't been reliable. Partly because it has a more complex install process than more conventional ones.

**Comment by tinganho** [comment]
@focusaurus I launched L10ns v2.1 now. Could you try it out? I removed the install report file.

**Comment by focusaurus** [comment]
Well on my ubuntu server I get the cldr-data issue with running out of memory and getting killed by the linux OOM killer while trying to unzip the cldr-data zip file, but other than that I don't see the install report error anymore. On OSX v2.1 installs OK. Thanks!

**Comment by tinganho** [comment]
@focusaurus I will report the issue to `cldr-data-download` and see if we can fix the buffer overload problem.

**Comment by focusaurus** [comment]
It's already tracked in [adm-zip here](https://github.com/cthackers/adm-zip/issues/129). I suspect the most realistic solution is for cldr-data-downloader to switch to another module for streaming unzips. The adm-zip maintainer hasn't responded and to have coded such a facepalm in the first place is a red flag.
