### ISSUE TITLE
Usage of translation function inside value object of another translation function is not detected

### ISSUE THREAD

**Issue by comx** [tinganho/l10ns#113]
```
l('contactPage.callUs', {phone: l('contactPage.phone')})
```
In the above example the 'l10ns update' will ignore the 'contactPage.phone' label usage and will delete it if it's the only one in the code. Can you point me in the right direction to fix it?

**Comment by tinganho** [comment]
@comx this is by design. It is really hard to fix this problem. I can let `l10ns` use a JS parser to fix this problem which I think is the only way to fix this problem along with other related problems. Though then I lose the flexibility of just a simple regexp. With a simple regexp I can parse not only JS but many compiled to JS languages like TypeScript and CoffeScript.

**Comment by tinganho** [comment]
I forgot to point out the solution which I already think you know is to declare a variable before one of the translation functions and then pass it as an argument.

**Comment by comx** [comment]
I see. Thanks for response.
