### ISSUE TITLE
Use req.locals.l in docs

### ISSUE THREAD

**Issue by focusaurus** [tinganho/l10ns#74]
The docs for express integration have:

```
app.configure(function(req, res, next) {
  global.l = requireLocalization(req.cookies.locale);
});
```

I'd suggest changing this to the following to ensure request-specific data (the cookie's locale value) doesn't leak globally and contaminate unrelated requests:

```
app.configure(function(req, res, next) {
  req.locals.l = requireLocalization(req.cookies.locale);
});
```

**Comment by tinganho** [comment]
@focusaurus seems reasonable let me just try it out first.

**Comment by tinganho** [comment]
@focusaurus I have now made this change. Though I wrote a new middleware to handle it. I recommend using [request-language](https://github.com/tinganho/express-request-language) for figuring out a request's language using `Accept-Language` header at the first request and using stored cookie in all other.

I decided to use `req.localizations` instead of `req.locals.l` instead.
