### ISSUE TITLE
split into core, cli, web modules

### ISSUE THREAD

**Issue by focusaurus** [tinganho/l10ns#84]
At the moment I think the l10ns module is larger and has more things than the overall node/npm consensus would like (this is also my personal opinion/preference). I'd like to see something along these lines:

- core library containing the guts/plumbing of the code
  - also AFAICT there's no official programmatic API. I'd like to see that as well without needing strong coupling to commander.js, having to call `cli.initialize()` etc.
- CLI (depends on core)
- Web UI (depends on core)

At the moment l10ns occupies 169 MB when installed in my project. The second-largest library in my project, node-zip is 8.5 MB, for comparison.

**Comment by tinganho** [comment]
Sounds great @focusaurus, though splitting L10ns up has been on the plan. I want to do it as soon as I add new message markup API's.

The storage L10ns occupies seems like there are some extra fat that needs to be cut. Though there are some data repo:es that L10ns uses that are quite big. Like IANA and CLDR. The new parsed version of CLDR will be much bigger than current one near 496mb big vs. 83MB. Though there is a benefit of having a parsed version vs non-parsed and that is that you don't need to parse during runtime. The speed of compiling and parsing have improved a lot, a couple of X, because of this. The compiled output will remain the same.

I will inspect if I can cut more fat from the project.

**Comment by tinganho** [comment]
The web interface will definitely be split out in a future version.
